name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change to your main branch if different
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'  # Use the version specified in your project

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          # Here you can add your test command if you have any
          # For example, if you use pytest, you can run:
          # pytest tests/
          echo "No tests defined"  # Replace with your test command

      - name: Build Docker image
        run: |
          docker build -t your-docker-image-name .

      - name: Push Docker image to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
          docker push your-docker-image-name

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job completes before deploying
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'latest'  # Specify a version if needed

      - name: Deploy to EKS
        env:
          KUBECONFIG: ${{ secrets.KUBECONFIG }}  # Add your Kubeconfig as a secret
        run: |
          kubectl apply -f configs/eks-deployment.yaml
